config/routes.rb
Rails.application.routes.draw do
  # GET /about
  get "about", to: "about#index"

  # GET /sing_up
  get "sing_up", to: "registrations#new"
  # post /sing_up
  post "sing_up", to: "registrations#create"

  # GET /sing_in
  get "sing_in", to: "sessions#new"
  # post /sing_in
  post "sing_in", to: "sessions#create"

  # GET /password
  get "password", to: "passwords#edit", as: "edit_password"
  # patch /passwords
  patch "password", to: "passwords#update"

  # GET /password/reset
  get "password/reset", to: "passwords_reset#new"
  # patch /passwords/reset
  post "password/reset", to: "passwords_reset#create"
  # delete /logout
  delete "logout", to: "sessions#destroy"
  # GET /
  root to: "main#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/Current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# email:string
# password_digest:string
#
# password_digest virtual
# password_confirmation:string virtual
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, format: { with: /\A(\S+)@(.+)\.(\S+)\z/, message: "must be valid email"}


end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  def require_user_logged_in!
    redirect_to sing_up_path, alert:  "Uou must be signed in to do that." if Current.user.nil?
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_user_logged_in!

  def edit

  end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: 'Passwords updated successfully'
    else
      render :edit
    end

  end

    private

    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/passwords_reset_controller.rb
class PasswordsResetController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])

    if user.present?
      PasswordMailer.with(user: @user).reset.deliver_now
    end

      redirect_to root_path, notice: "sent a link to reset your Passwords"
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice:  "Successfully created"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in successfully"
    else
      flash[:alert] = 'Invalid email or password'
      render :new
    end
  end


  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>about</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterBot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render partial: "shared/navbar" %>
  <div class="container">
    <%= render partial: "shared/flash" %>

    <%= yield %>
  </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
  <h1>Welcome to  Twitter bot </h1>
</div>

app/views/passwords_reset/new.html.erb
<h1>Forgot your password</h1>
<%= form_with model: @user, url: password_reset_path do |form| %>

  <div class="mb-3">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control", placeholder: "s@" %>
  </div>

  <div class="mb-3">
    <%= form.submit "Reset Password",  class: "btn btn-primary" %>
  </div>

<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
<div class="alert alert-primary mt-4" role="alert">
  <%= flash[:notice].inspect %>
</div>
<% end %>

<div class="alert alert-warning mt-4" role="alert">
  <%= flash[:alert].inspect %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Navbar", root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
<!--          <a class="nav-link active" aria-current="page" href="/">Home</a>-->
          <%= link_to "Home", root_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link"%>
        </li>
      </ul>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
      <% if Current.user %>
          <li class="nav-item">
            <%= link_to  Current.user.email, edit_password_path %>
          </li>
          <li class="nav-item">
        <%= button_to "Logged", logout_path, method: :delete, class: "btn btn-outline-secondary"%>
          </li>
      <% else %>
          <li class="nav-item">
            <%= link_to "sing up", sing_up_path, class: "nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "sing in", sing_in_path, class: "nav-link"%>
          </li>
      <% end %>
      </ul>

    </div>
  </div>
</nav>